#!/usr/bin/env node
// Derive the browser page-runtime string served at /app/runtime.js from its real,
// type-checked/linted/unit-tested source (src/runtime/browser/runtime.browser.js).
//
// WHY THIS EXISTS
// The runtime used to ship as a ~1,900-line `String.raw` blob inside pages.ts, so
// tsc/biome/tests saw an opaque string, not code (#291). It is now authored as a
// real module and this generator emits the exact string the server embeds — the
// same "generated derived artifact + `git diff --exit-code` in CI" pattern
// AGENTS.md already uses for other derived files. Authoring the runtime as code
// buys type-checking, linting and unit tests; emitting it as a checked-in string
// preserves the single-file / no-bundler / no-asset-path embed that lets the same
// module travel identically under Node, Deno and the embedded host.
//
// SINGLE SOURCE OF TRUTH
// The one runtime→CSS shared value, the mobile breakpoint, lives once as
// `MOBILE_MAX_WIDTH` in pages.ts (which interpolates it into the shell CSS
// @media). The runtime source carries a `__MOBILE_MAX_WIDTH__` placeholder that
// this generator substitutes with that same value, so the JS mode-switch and the
// CSS card-flip can never drift on where "narrow" begins.
//
// Usage:  node scripts/gen-runtime.mjs [--check]
//   (default) regenerate src/runtime/core/modules/runtime.gen.ts
//   --check   exit non-zero if the checked-in artifact is stale (for CI); no write.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const SRC = resolve(HERE, "../src/runtime/browser/runtime.browser.js");
const PAGES = resolve(HERE, "../src/runtime/core/modules/pages.ts");
const OUT = resolve(HERE, "../src/runtime/core/modules/runtime.gen.ts");
// The shared form-js renderer (ADR 0026, extended by #457): one authored/tested
// browser module, embedded as a <script> by BOTH the taskInbox surface and the
// pages shell so the two never fork the renderer. Emitted the same way as the
// runtime string above.
const SRC_FORMJS = resolve(HERE, "../src/runtime/browser/formjs.browser.js");
const OUT_FORMJS = resolve(HERE, "../src/runtime/core/modules/formjs.gen.ts");

const PLACEHOLDER = "__MOBILE_MAX_WIDTH__";

function fail(msg) {
  console.error(`gen-runtime: ${msg}`);
  process.exit(1);
}

// Read the single source of truth for the mobile breakpoint from pages.ts. The
// generator derives from it rather than duplicating "640px" — a change there
// flows here and CI's --check catches a forgotten regeneration.
function mobileBreakpoint() {
  const pages = readFileSync(PAGES, "utf8");
  const m = pages.match(/const\s+MOBILE_MAX_WIDTH\s*=\s*["']([^"']+)["']/);
  if (!m) fail(`could not find 'const MOBILE_MAX_WIDTH = "…"' (single- or double-quoted) in ${PAGES}`);
  return m[1];
}

function build() {
  const source = readFileSync(SRC, "utf8");
  if (!source.includes(PLACEHOLDER)) {
    fail(`runtime source is missing the ${PLACEHOLDER} placeholder — did the breakpoint wiring change?`);
  }
  const breakpoint = mobileBreakpoint();
  // The runtime is a single ES module with no bundling required; the only
  // build-time transform is substituting the shared breakpoint placeholder.
  const served = source.split(PLACEHOLDER).join(breakpoint);
  const banner =
    "// @generated by scripts/gen-runtime.mjs — DO NOT EDIT.\n" +
    "// Source: src/runtime/browser/runtime.browser.js (the type-checked/linted/tested\n" +
    "// browser runtime). Regenerate with `npm run gen:runtime`; CI enforces this file\n" +
    "// is byte-identical to a fresh generation via `git diff --exit-code` (npm run check:runtime).\n\n";
  return `${banner}export const RENDERER_JS: string = ${JSON.stringify(served)};\n`;
}

// Emit the shared form-js renderer as an embeddable <script> string. The authored
// module ends with an ESM `export { ... }` (so it can be unit-tested under Node);
// a classic <script> can't carry an `export`, so strip that statement — the
// module still exposes its API via the `globalThis.NanoFormJs` assignment that
// both host surfaces consume.
function buildFormjs() {
  const source = readFileSync(SRC_FORMJS, "utf8");
  const stripped = source.replace(/\nexport \{ buildField, renderForm \};\n/, "\n");
  if (stripped === source) {
    fail("formjs source is missing its 'export { buildField, renderForm };' statement — did the exports change?");
  }
  const banner =
    "// @generated by scripts/gen-runtime.mjs — DO NOT EDIT.\n" +
    "// Source: src/runtime/browser/formjs.browser.js (the shared, type-checked/linted/tested\n" +
    "// form-js renderer). Regenerate with `npm run gen:runtime`; CI enforces this file\n" +
    "// is byte-identical to a fresh generation via `git diff --exit-code` (npm run check:runtime).\n\n";
  return `${banner}export const FORMJS_JS: string = ${JSON.stringify(stripped)};\n`;
}

/** Write, or (in --check mode) assert freshness of, one generated artifact. */
function emit(outPath, contents, label, check) {
  if (check) {
    let current = "";
    try {
      current = readFileSync(outPath, "utf8");
    } catch {
      fail(`${outPath} is missing. Run 'npm run gen:runtime' and commit it.`);
    }
    if (current !== contents) {
      fail(`${label} is stale. Run 'npm run gen:runtime' and commit the result.`);
    }
    console.log(`gen-runtime: ${label} is up to date.`);
    return;
  }
  writeFileSync(outPath, contents);
  console.log(`gen-runtime: wrote ${outPath} (${contents.length} bytes).`);
}

function main() {
  const check = process.argv.includes("--check");
  emit(OUT, build(), "runtime.gen.ts", check);
  emit(OUT_FORMJS, buildFormjs(), "formjs.gen.ts", check);
}

main();
