// GENERATED by scripts/gen-node-registry.mjs — do not edit by hand.
//
// The barrel of built-in flow-node kind modules. Importing this module runs
// every kind's `registerNodeKind(...)` side effect, populating the dispatch
// table `makeBuilder`/`walkNodes`/the emitter route through. A new kind is
// picked up automatically by re-running the generator (a prebuild step) — no
// hand-edit here.

import "./boundary.js";
import "./branch.js";
import "./break.js";
import "./continue.js";
import "./forEach.js";
import "./human.js";
import "./loop.js";
import "./parallel.js";
import "./race.js";
import "./run.js";
import "./signal.js";
import "./switch.js";
import "./task.js";
import "./timer.js";
