import { test } from "node:test";
import assert from "node:assert/strict";
import {
  deriveMessageBindings,
  emitMessageBindings,
  scanModelMessages,
  type MessageIo,
} from "./messages.ts";

// Goldens captured byte-for-byte from the console's canonical `emitMessageBindings`
// (server/src/console/domain_types.ts) so this port is provably a drop-in (ADR 0053).
const GOLD_EMPTY =
  "// AUTO-GENERATED by nanobpmn from the process model (ADR 0040 slice 2).\n" +
  "// The bridge from a `bpmn:message`'s data envelope to the message type system:\n" +
  "// each named message maps to the TS type of its payload, so the typed\n" +
  "// `publishMessage` types a call by its message name. Do not edit — regenerated\n" +
  "// from the model. Erased to plain JS at compile.\n" +
  "\n" +
  "\n" +
  "/** Untyped fallback payload for a message that declares no envelope type. */\n" +
  "export type MessageVars = Record<string, unknown>;\n" +
  "\n" +
  "/** Every declared message `name` (ADR 0040 slice 2): the model-derived set the\n" +
  " * typed `publishMessage` accepts, so `name` autocompletes and rejects unknown messages. */\n" +
  "export type MessageName = string;\n" +
  "\n" +
  "/** Payload (`variables`) per declared message, keyed by `name`. */\n" +
  "export type MessagePayloads = Record<never, never>;\n";

const GOLD_NAMESONLY =
  "// AUTO-GENERATED by nanobpmn from the process model (ADR 0040 slice 2).\n" +
  "// The bridge from a `bpmn:message`'s data envelope to the message type system:\n" +
  "// each named message maps to the TS type of its payload, so the typed\n" +
  "// `publishMessage` types a call by its message name. Do not edit — regenerated\n" +
  "// from the model. Erased to plain JS at compile.\n" +
  "\n" +
  "\n" +
  "/** Untyped fallback payload for a message that declares no envelope type. */\n" +
  "export type MessageVars = Record<string, unknown>;\n" +
  "\n" +
  "/** Every declared message `name` (ADR 0040 slice 2): the model-derived set the\n" +
  " * typed `publishMessage` accepts, so `name` autocompletes and rejects unknown messages. */\n" +
  "export type MessageName = \"OrderPlaced\" | \"OrderShipped\";\n" +
  "\n" +
  "/** Payload (`variables`) per declared message, keyed by `name`. */\n" +
  "export type MessagePayloads = Record<never, never>;\n";

const GOLD_TYPED =
  "// AUTO-GENERATED by nanobpmn from the process model (ADR 0040 slice 2).\n" +
  "// The bridge from a `bpmn:message`'s data envelope to the message type system:\n" +
  "// each named message maps to the TS type of its payload, so the typed\n" +
  "// `publishMessage` types a call by its message name. Do not edit — regenerated\n" +
  "// from the model. Erased to plain JS at compile.\n" +
  "\n" +
  "import type { DomainTypes } from \"./domain-rows.d.ts\";\n" +
  "\n" +
  "/** Untyped fallback payload for a message that declares no envelope type. */\n" +
  "export type MessageVars = Record<string, unknown>;\n" +
  "\n" +
  "/** Every declared message `name` (ADR 0040 slice 2): the model-derived set the\n" +
  " * typed `publishMessage` accepts, so `name` autocompletes and rejects unknown messages. */\n" +
  "export type MessageName = \"OrderPlaced\";\n" +
  "\n" +
  "/** Payload (`variables`) per declared message, keyed by `name`. */\n" +
  "export interface MessagePayloads {\n" +
  "  \"OrderPlaced\": DomainTypes[\"Order\"];\n" +
  "}\n";

const GOLD_MIXED =
  "// AUTO-GENERATED by nanobpmn from the process model (ADR 0040 slice 2).\n" +
  "// The bridge from a `bpmn:message`'s data envelope to the message type system:\n" +
  "// each named message maps to the TS type of its payload, so the typed\n" +
  "// `publishMessage` types a call by its message name. Do not edit — regenerated\n" +
  "// from the model. Erased to plain JS at compile.\n" +
  "\n" +
  "import type { DomainTypes } from \"./domain-rows.d.ts\";\n" +
  "\n" +
  "/** Untyped fallback payload for a message that declares no envelope type. */\n" +
  "export type MessageVars = Record<string, unknown>;\n" +
  "\n" +
  "/** Every declared message `name` (ADR 0040 slice 2): the model-derived set the\n" +
  " * typed `publishMessage` accepts, so `name` autocompletes and rejects unknown messages. */\n" +
  "export type MessageName = \"OrderPlaced\" | \"Ping\";\n" +
  "\n" +
  "/** Payload (`variables`) per declared message, keyed by `name`. */\n" +
  "export interface MessagePayloads {\n" +
  "  \"OrderPlaced\": DomainTypes[\"Order\"];\n" +
  "}\n";

test("emitMessageBindings: no messages → string union + empty payloads (matches console)", () => {
  assert.equal(emitMessageBindings([], []), GOLD_EMPTY);
});

test("emitMessageBindings: names-only → finite union, no import (matches console)", () => {
  const out = emitMessageBindings(
    [{ messageName: "OrderPlaced" }, { messageName: "OrderShipped" }],
    [],
  );
  assert.equal(out, GOLD_NAMESONLY);
});

test("emitMessageBindings: a declared envelope maps to DomainTypes (matches console)", () => {
  const out = emitMessageBindings([{ messageName: "OrderPlaced", inputType: "Order" }], ["Order"]);
  assert.equal(out, GOLD_TYPED);
});

test("emitMessageBindings: an undeclared envelope type is omitted from payloads (matches console)", () => {
  const out = emitMessageBindings(
    [
      { messageName: "OrderPlaced", inputType: "Order" },
      { messageName: "Ping", inputType: "NotDeclared" },
    ],
    ["Order", "Receipt"],
  );
  assert.equal(out, GOLD_MIXED);
});

const XML = `<?xml version="1.0"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"
                  xmlns:zeebe="http://camunda.org/schema/zeebe/1.0">
  <bpmn:message id="M1" name="OrderPlaced">
    <bpmn:extensionElements>
      <zeebe:properties>
        <zeebe:property name="io.nanobpm.dataEnvelope.in" value="Order" />
      </zeebe:properties>
    </bpmn:extensionElements>
  </bpmn:message>
  <bpmn:message id="M2" name="Ping" />
</bpmn:definitions>`;

test("scanModelMessages extracts message name + envelope; a self-closing message is name-only", () => {
  const m = scanModelMessages(XML);
  const placed = m.find((x) => x.messageName === "OrderPlaced");
  assert.ok(placed);
  assert.ok(placed);
  assert.equal(placed.inputType, "Order");
  const ping = m.find((x) => x.messageName === "Ping");
  assert.ok(ping);
  assert.ok(ping);
  assert.equal(ping.inputType, undefined);
});

test("scanModelMessages drops a message with an empty/absent name", () => {
  assert.deepEqual(scanModelMessages(`<bpmn:message name="" />`), []);
  assert.deepEqual(scanModelMessages(`<bpmn:message id="x" />`), []);
});

test("deriveMessageBindings is deterministic and emits message-io.d.ts", () => {
  const models = [{ path: "processes/orders.bpmn", xml: XML }];
  const a1 = deriveMessageBindings(models, ["Order"]);
  const a2 = deriveMessageBindings(models, ["Order"]);
  assert.deepEqual(a1, a2);
  assert.equal(a1[0].path, "nano-generated/message-io.d.ts");
  assert.match(a1[0].content, /"OrderPlaced": DomainTypes\["Order"\]/);
});

test("deriveMessageBindings sorts by name and merges envelopes first-wins across models", () => {
  // Same message declared in two models: the first (path order) carries the envelope,
  // the later re-declaration (no envelope) must not clear it (mirrors the Rust fill).
  const a = `<bpmn:message name="Zebra" />`;
  const b1 = `<bpmn:message name="Alpha"><zeebe:property name="io.nanobpm.dataEnvelope.in" value="Order" /></bpmn:message>`;
  const b2 = `<bpmn:message name="Alpha" />`;
  const models = [
    { path: "processes/2-second.bpmn", xml: b2 },
    { path: "processes/1-first.bpmn", xml: b1 + a },
  ];
  const content = deriveMessageBindings(models, ["Order"])[0].content;
  // Sorted by name: Alpha before Zebra.
  assert.match(content, /export type MessageName = "Alpha" \| "Zebra";/);
  // First-wins: Alpha keeps its Order envelope despite the later name-only re-declaration.
  assert.match(content, /"Alpha": DomainTypes\["Order"\]/);
});
