// Deriver: BPMN models → `message-io.d.ts`, the message-payload type map (ADR 0040 slice 2).
// Scans each process for `bpmn:message` envelopes and maps each message name to its declared
// payload type. It emits the SAME `message-io.d.ts` the console generates (a faithful port of
// `emitMessageBindings` in the server's domain_types.ts), so the toolkit is a drop-in for the
// IDE's codegen (ADR 0053). The static typed-`publishMessage` wrapper (`messages.ts`) never
// changes with the model, so — like the worker SDK — it is a package/runtime concern, not a
// derived artifact; only the model-derived `message-io.d.ts` is emitted here.

import type { DerivedArtifact, Deriver } from "../artifact.ts";
import { GENERATED_DIR } from "../artifact.ts";
import { byModelPath, DOMAIN_DTS, typeRefFor, type ModelSource } from "./worker-io.ts";

/** Filename the console uses for the derived message-payload map; kept identical (drop-in). */
export const MESSAGE_BINDINGS_DTS = "message-io.d.ts";
/** The generated typed-`publishMessage` wrapper's basename — re-exports the worker SDK's
 * `publishMessage` with a messageName-keyed typed signature. */
export const MESSAGE_BINDINGS_TS = "messages.ts";

const ENVELOPE_IN = "io.nanobpm.dataEnvelope.in";
const ENVELOPE_OUT = "io.nanobpm.dataEnvelope.out";

/** One message-IO entry scanned from a model: a `bpmn:message` name plus the envelope
 * type refs it carries. `inputType` is the received payload (what a `publishMessage`
 * caller sends); `outputType` is reserved. Mirrors the Rust `MessageIo`. */
export interface MessageIo {
  messageName: string;
  inputType?: string;
  outputType?: string;
}

/** The binding shape the emitter reads. Identical to a scanned `MessageIo`, so it is an
 * alias — one canonical shape, no second declaration to drift (the console keeps the two
 * apart only because its scan output is Rust and its emitter input is TS). */
export type MessageBindingDecl = MessageIo;

function attr(tag: string, name: string): string | undefined {
  const m = tag.match(new RegExp(`\\b${name}\\s*=\\s*"([^"]*)"`));
  return m ? m[1] : undefined;
}

/** An envelope ref is trimmed; an empty/whitespace value contributes nothing (mirrors the
 * Rust `envelope_ref`). A message name, by contrast, is a correlation identity matched
 * verbatim by the engine, so it is NOT trimmed — only an absent/empty name is dropped. */
function envelopeRef(value: string | undefined): string | undefined {
  const v = value?.trim();
  return v ? v : undefined;
}

/** Scan one BPMN document for `bpmn:message` envelopes. Handles both a self-closing
 * `<bpmn:message name=.. />` (name only — completes the `MessageName` union) and an open
 * message whose body carries the `io.nanobpm.dataEnvelope.in/out` `zeebe:property`. */
export function scanModelMessages(xml: string): MessageIo[] {
  const out: MessageIo[] = [];
  const blockRe = /<bpmn:message\b([^>]*?)(?:\/>|>([\s\S]*?)<\/bpmn:message>)/g;
  let m: RegExpExecArray | null;
  while ((m = blockRe.exec(xml)) !== null) {
    const name = attr(`<x ${m[1]}>`, "name");
    if (name == null || name.length === 0) continue;
    const io: MessageIo = { messageName: name };
    const body = m[2] ?? "";
    const propRe = /<zeebe:property\b[^>]*>/g;
    let p: RegExpExecArray | null;
    while ((p = propRe.exec(body)) !== null) {
      const pname = attr(p[0], "name");
      if (pname === ENVELOPE_IN) io.inputType = envelopeRef(attr(p[0], "value"));
      else if (pname === ENVELOPE_OUT) io.outputType = envelopeRef(attr(p[0], "value"));
    }
    out.push(io);
  }
  return out;
}

// --- Faithful port of the console's emitMessageBindings (domain_types.ts) so the emitted
//     message-io.d.ts is byte-compatible with the IDE's own codegen. ---

/** Emit `message-io.d.ts` from message bindings + the set of declared domain type ids.
 * Each named message joins the `MessageName` union; a message whose envelope names a
 * declared type also maps to it in `MessagePayloads` (else falls back to `MessageVars`). */
export function emitMessageBindings(
  messages: MessageBindingDecl[],
  declaredTypeIds: Iterable<string>,
): string {
  const declared = new Set(declaredTypeIds);
  const propKey = (m: string) => JSON.stringify(m);
  const names = [
    ...new Set(
      messages
        .map((m) => m?.messageName)
        .filter((n): n is string => typeof n === "string" && n.length > 0),
    ),
  ];
  const nameUnion = names.length > 0
    ? names.map((n) => JSON.stringify(n)).join(" | ")
    : "string";
  const payloads: string[] = [];
  for (const m of messages) {
    if (typeof m?.messageName !== "string" || m.messageName.length === 0) continue;
    const ref = typeRefFor(m.inputType, declared);
    if (ref) payloads.push(`  ${propKey(m.messageName)}: ${ref};`);
  }

  const header =
    "// AUTO-GENERATED by nanobpmn from the process model (ADR 0040 slice 2).\n" +
    "// The bridge from a `bpmn:message`'s data envelope to the message type system:\n" +
    "// each named message maps to the TS type of its payload, so the typed\n" +
    "// `publishMessage` types a call by its message name. Do not edit — regenerated\n" +
    "// from the model. Erased to plain JS at compile.\n";

  const needsRegistry = payloads.length > 0;
  const importTypes = needsRegistry
    ? `import type { DomainTypes } from "./${DOMAIN_DTS}";\n`
    : "";

  const payloadsIface = payloads.length > 0
    ? `export interface MessagePayloads {\n${payloads.join("\n")}\n}\n`
    : `export type MessagePayloads = Record<never, never>;\n`;

  return `${header}\n` +
    importTypes +
    `\n/** Untyped fallback payload for a message that declares no envelope type. */\n` +
    `export type MessageVars = Record<string, unknown>;\n\n` +
    `/** Every declared message \`name\` (ADR 0040 slice 2): the model-derived set the\n` +
    ` * typed \`publishMessage\` accepts, so \`name\` autocompletes and rejects unknown messages. */\n` +
    `export type MessageName = ${nameUnion};\n\n` +
    `/** Payload (\`variables\`) per declared message, keyed by \`name\`. */\n` +
    payloadsIface;
}

/**
 * Derive `nano-generated/message-io.d.ts` from BPMN models. Messages are aggregated the way
 * the console's Rust scan does (a `BTreeMap` keyed by name): deduped by name, sorted by name,
 * with the envelope type refs merged first-wins across models — so the derived output matches
 * the host's `derivedMessages` for the same models. `declaredTypeIds` is the manifest `types`
 * key set; a message only gets a typed payload when its envelope names a declared type.
 */
export function deriveMessageBindings(
  models: ModelSource[],
  declaredTypeIds: Iterable<string> = [],
): DerivedArtifact[] {
  const byName = new Map<string, MessageBindingDecl>();
  for (const model of [...models].sort(byModelPath)) {
    for (const msg of scanModelMessages(model.xml)) {
      const existing = byName.get(msg.messageName);
      if (!existing) {
        byName.set(msg.messageName, {
          messageName: msg.messageName,
          inputType: msg.inputType,
          outputType: msg.outputType,
        });
      } else {
        // First-wins merge of the envelope refs (mirrors the Rust `fill`).
        if (existing.inputType == null) existing.inputType = msg.inputType;
        if (existing.outputType == null) existing.outputType = msg.outputType;
      }
    }
  }
  const messages = [...byName.values()].sort((a, b) =>
    a.messageName < b.messageName ? -1 : a.messageName > b.messageName ? 1 : 0
  );
  const content = emitMessageBindings(messages, declaredTypeIds);
  return [{ path: `${GENERATED_DIR}/${MESSAGE_BINDINGS_DTS}`, content }];
}

export const messagesDeriver: Deriver<{ models: ModelSource[]; declaredTypeIds: Iterable<string> }> = {
  id: "model->message-io",
  describe: "Derive message-io.d.ts (bpmn:message name + envelope payload) from BPMN models.",
  derive: ({ models, declaredTypeIds }) => deriveMessageBindings(models, declaredTypeIds),
};

/**
 * The static typed-`publishMessage` wrapper (`messages.ts`). It re-exports the worker SDK's
 * `publishMessage` (and its option/result types) and overrides `publishMessage` with a signature
 * that keys off the `name` string literal: when a message is present in the generated
 * `MessagePayloads` (ADR 0040 slice 2), the call's `variables` are typed from the declared domain
 * type; otherwise they fall back to `MessageVars`. The body is a pass-through — the wire stays
 * untyped JSON. This file never changes with the model, so it is written verbatim (unlike the
 * regenerated `message-io.d.ts`). A byte-faithful port of the console's
 * `emitMessageBindingsRuntime`.
 */
export function emitMessageBindingsRuntime(): string {
  return "// AUTO-GENERATED by nanobpmn (ADR 0040 slice 2): the typed `publishMessage`.\n" +
    "// Re-exports the worker SDK's `publishMessage` and overrides it with a\n" +
    "// messageName-keyed typed signature (variables typed from the message's declared\n" +
    "// envelope). Erased to a pass-through at runtime. Do not edit.\n\n" +
    `import type { MessageName, MessagePayloads, MessageVars } from "./${MESSAGE_BINDINGS_DTS}";\n` +
    `import type { PublishMessageOptions, PublishMessageResult } from "./worker-sdk.ts";\n` +
    `import { publishMessage as publishMessageRaw } from "./worker-sdk.ts";\n\n` +
    `export type { PublishMessageOptions, PublishMessageResult } from "./worker-sdk.ts";\n\n` +
    `type PayloadFor<K extends MessageName> = K extends keyof MessagePayloads ? MessagePayloads[K] : MessageVars;\n\n` +
    `/**\n` +
    ` * Typed \`publishMessage\`: \`name\` is constrained to the model's declared message\n` +
    ` * names (\`MessageName\`, ADR 0040 slice 2) so it autocompletes and rejects unknown\n` +
    ` * messages, and \`variables\` are typed from the message's declared envelope. A\n` +
    ` * declared message with no domain type falls back to MessageVars.\n` +
    ` */\n` +
    `export function publishMessage<K extends MessageName>(\n` +
    `  name: K,\n` +
    `  opts?: PublishMessageOptions<PayloadFor<K> & object>,\n` +
    `): Promise<PublishMessageResult> {\n` +
    `  // biome-ignore lint/plugin: generic-to-raw erasure at the message-SDK boundary; the wire stays untyped JSON (ADR 0040 slice 2).\n` +
    `  return publishMessageRaw(name, opts as unknown as PublishMessageOptions);\n` +
    `}\n`;
}
