// Deriver: BPMN models → `meta.ts`, the typed model-metadata accessor (`@nanobpm/meta`,
// ADR 0040 §5). Scans each process for `nano:meta` key/value siblings of the `nano:shapes`
// container and folds them into a single app-wide record. It emits the SAME `meta.ts` the
// console generates (a faithful port of `foldMeta`/`emitMeta` in the server's domain_types.ts),
// so the toolkit is a drop-in for the IDE's codegen (ADR 0053).

import type { DerivedArtifact, Deriver } from "../artifact.ts";
import { GENERATED_DIR } from "../artifact.ts";
import { byModelPath, type ModelSource } from "./worker-io.ts";

/** Basename the console uses for the generated accessor; kept identical (drop-in). */
export const META_TS = "meta.ts";

/** One model-level metadata entry (`nano:meta`), tagged with its defining process for
 * the `model:<processId>` provenance (ADR 0040 §5). `process` is carried for the fuse;
 * the emitted `meta.ts` folds on key/value only. */
export interface MetaDecl {
  process?: string;
  key: string;
  value: string;
}

function attr(tag: string, name: string): string | undefined {
  const m = tag.match(new RegExp(`\\b${name}\\s*=\\s*"([^"]*)"`));
  return m ? m[1] : undefined;
}

function processId(xml: string): string | undefined {
  const m = xml.match(/<[\w.-]*:?process\b[^>]*>/);
  return m ? attr(m[0], "id") : undefined;
}

// A `nano:shape` carrier (`<...:shape>…</...:shape>`, and self-closing) — meta is only
// recognised *outside* a shape carrier (its op children, e.g. `extend`, are a different
// vocabulary), so strip carriers before matching `nano:meta` (mirrors envelope_scan.rs).
const SHAPE_BLOCK_RE = /<([\w.-]*:)?shape\b[^>]*(?:\/>|>[\s\S]*?<\/\1?shape\s*>)/g;
// A `nano:meta` element (any namespace prefix; matches the Rust local-name scan).
const META_RE = /<([\w.-]*:)?meta\b([^>]*?)\/?>/g;

/** Scan one BPMN document for model-level `nano:meta` key/value entries, in document
 * order, tagged with the enclosing process. A meta with no `key` attribute is ignored;
 * a missing `value` folds to the empty string (matches envelope_scan.rs). */
export function scanModelMeta(xml: string): MetaDecl[] {
  const proc = processId(xml);
  const withoutShapes = xml.replace(SHAPE_BLOCK_RE, "");
  const out: MetaDecl[] = [];
  let m: RegExpExecArray | null;
  while ((m = META_RE.exec(withoutShapes)) !== null) {
    const key = attr(`<x ${m[2]}>`, "key");
    if (key == null) continue;
    out.push({ process: proc, key, value: attr(`<x ${m[2]}>`, "value") ?? "" });
  }
  return out;
}

// --- Faithful port of the console's foldMeta/emitMeta (domain_types.ts) so the emitted
//     meta.ts is byte-compatible with the IDE's own codegen. ---

function isIdent(name: string): boolean {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name);
}

/** Fold the scanned model-level metadata into a single key→value record. When two models
 * declare the same key the last (scan order) wins. Empty keys are ignored. The accumulator
 * is a **null-prototype** dict so user-authored keys (including `__proto__`) round-trip
 * deterministically as own data properties. */
export function foldMeta(metas: MetaDecl[]): Record<string, string> {
  const out: Record<string, string> = Object.create(null);
  for (const m of metas) {
    const key = (m?.key ?? "").trim();
    if (!key) continue;
    out[key] = m.value ?? "";
  }
  return out;
}

/** Emit `meta.ts`: the typed model-metadata accessor (`@nanobpm/meta`, ADR 0040 §5).
 * `AppMeta` keys the declared metadata as string-literal properties; `appMeta` is the
 * concrete null-prototype record; the overloaded `meta()` returns the typed value for a
 * known key and `string | undefined` for a dynamic one. Strip-safe (ADR 0036). */
export function emitMeta(metas: MetaDecl[]): string {
  const folded = foldMeta(metas);
  const keys = Object.keys(folded);
  const propKey = (k: string) => (isIdent(k) ? k : JSON.stringify(k));
  const header =
    "// AUTO-GENERATED by nanobpmn from the process model (ADR 0040 §5): the typed\n" +
    "// model-metadata accessor. Each `nano:meta` key/value the models declare becomes\n" +
    "// a checked `AppMeta` property, so `meta(key)` is typed and app-wide queryable\n" +
    "// without a second store. Do not edit — regenerated from the model.\n\n";
  const iface = keys.length > 0
    ? `export interface AppMeta {\n${keys.map((k) => `  ${propKey(k)}: string;`).join("\n")}\n}\n`
    : `export type AppMeta = Record<string, never>;\n`;
  const constDecl = keys.length > 0
    ? `export const appMeta: AppMeta = (() => {\n` +
      `  const m: AppMeta = Object.create(null);\n` +
      keys.map((k) => `  m[${JSON.stringify(k)}] = ${JSON.stringify(folded[k])};`).join("\n") +
      `\n  return m;\n})();\n`
    : `export const appMeta: AppMeta = Object.create(null);\n`;
  const accessor =
    `\n/** Read a model-level metadata value. A declared key is typed; a dynamic key\n` +
    ` * returns \`string | undefined\`. */\n` +
    `export function meta<K extends keyof AppMeta>(key: K): AppMeta[K];\n` +
    `export function meta(key: string): string | undefined;\n` +
    `export function meta(key: string): string | undefined {\n` +
    `  return Reflect.get(appMeta, key);\n` +
    `}\n`;
  return `${header}/** Every model-level metadata key the App's models declare (ADR 0040 §5). */\n` +
    iface + "\n" + constDecl + accessor;
}

/**
 * Derive `nano-generated/meta.ts` from BPMN models. Deterministic: models are scanned in
 * path order, then their `nano:meta` entries folded (last write wins) into the accessor.
 */
export function deriveMeta(models: ModelSource[]): DerivedArtifact[] {
  const metas: MetaDecl[] = [];
  for (const model of [...models].sort(byModelPath)) {
    metas.push(...scanModelMeta(model.xml));
  }
  return [{ path: `${GENERATED_DIR}/${META_TS}`, content: emitMeta(metas) }];
}

export const metaDeriver: Deriver<{ models: ModelSource[] }> = {
  id: "model->meta",
  describe: "Derive meta.ts (the typed @nanobpm/meta accessor) from BPMN nano:meta entries.",
  derive: ({ models }) => deriveMeta(models),
};
