import { test } from "node:test";
import assert from "node:assert/strict";
import { deriveMeta, emitMeta, foldMeta, scanModelMeta, type MetaDecl } from "./meta.ts";

// Goldens captured byte-for-byte from the console's canonical `emitMeta`
// (server/src/console/domain_types.ts) so this port is provably a drop-in (ADR 0053).
const HEADER =
  "// AUTO-GENERATED by nanobpmn from the process model (ADR 0040 §5): the typed\n" +
  "// model-metadata accessor. Each `nano:meta` key/value the models declare becomes\n" +
  "// a checked `AppMeta` property, so `meta(key)` is typed and app-wide queryable\n" +
  "// without a second store. Do not edit — regenerated from the model.\n" +
  "\n" +
  "/** Every model-level metadata key the App's models declare (ADR 0040 §5). */\n";
const ACCESSOR =
  "\n/** Read a model-level metadata value. A declared key is typed; a dynamic key\n" +
  " * returns `string | undefined`. */\n" +
  "export function meta<K extends keyof AppMeta>(key: K): AppMeta[K];\n" +
  "export function meta(key: string): string | undefined;\n" +
  "export function meta(key: string): string | undefined {\n" +
  "  return Reflect.get(appMeta, key);\n" +
  "}\n";

const GOLDEN_EMPTY = HEADER +
  "export type AppMeta = Record<string, never>;\n\n" +
  "export const appMeta: AppMeta = Object.create(null);\n" +
  ACCESSOR;

const GOLDEN_MULTI = HEADER +
  "export interface AppMeta {\n  classification: string;\n  owner: string;\n}\n\n" +
  "export const appMeta: AppMeta = (() => {\n" +
  "  const m: AppMeta = Object.create(null);\n" +
  '  m["classification"] = "internal";\n' +
  '  m["owner"] = "ops";\n' +
  "  return m;\n})();\n" +
  ACCESSOR;

const GOLDEN_NONIDENT = HEADER +
  'export interface AppMeta {\n  "data-classification": string;\n}\n\n' +
  "export const appMeta: AppMeta = (() => {\n" +
  "  const m: AppMeta = Object.create(null);\n" +
  '  m["data-classification"] = "pii";\n' +
  "  return m;\n})();\n" +
  ACCESSOR;

const GOLDEN_PROTO = HEADER +
  "export interface AppMeta {\n  __proto__: string;\n}\n\n" +
  "export const appMeta: AppMeta = (() => {\n" +
  "  const m: AppMeta = Object.create(null);\n" +
  '  m["__proto__"] = "danger";\n' +
  "  return m;\n})();\n" +
  ACCESSOR;

test("emitMeta emits the empty accessor byte-for-byte (matches console)", () => {
  assert.equal(emitMeta([]), GOLDEN_EMPTY);
});

test("emitMeta emits declared keys in scan order byte-for-byte (matches console)", () => {
  const metas: MetaDecl[] = [
    { process: "Proc_a", key: "classification", value: "internal" },
    { process: "Proc_a", key: "owner", value: "ops" },
  ];
  assert.equal(emitMeta(metas), GOLDEN_MULTI);
});

test("emitMeta quotes non-identifier keys byte-for-byte (matches console)", () => {
  assert.equal(emitMeta([{ key: "data-classification", value: "pii" }]), GOLDEN_NONIDENT);
});

test("emitMeta handles a literal __proto__ key via a null-prototype dict (matches console)", () => {
  assert.equal(emitMeta([{ key: "__proto__", value: "danger" }]), GOLDEN_PROTO);
});

test("foldMeta: last declaration of a key wins; empty keys are dropped", () => {
  const folded = foldMeta([
    { key: "env", value: "staging" },
    { key: "  ", value: "ignored" },
    { key: "env", value: "prod" },
  ]);
  assert.equal(folded.env, "prod");
  assert.deepEqual(Object.keys(folded), ["env"]);
});

const XML = `<?xml version="1.0"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"
                  xmlns:nano="https://nanobpm.io/schema/shapes/1.0">
  <bpmn:process id="orders" isExecutable="true">
    <bpmn:extensionElements>
      <nano:shapes><nano:shape id="S"><nano:carry ref="Order" /></nano:shape></nano:shapes>
      <nano:meta key="classification" value="internal" />
      <nano:meta key="owner" value="ops" />
    </bpmn:extensionElements>
  </bpmn:process>
</bpmn:definitions>`;

test("scanModelMeta lifts nano:meta siblings in document order, tagged with the process", () => {
  assert.deepEqual(scanModelMeta(XML), [
    { process: "orders", key: "classification", value: "internal" },
    { process: "orders", key: "owner", value: "ops" },
  ]);
});

test("scanModelMeta does not mistake a shape's op children for model meta", () => {
  const xml = `<bpmn:process id="p"><bpmn:extensionElements>
    <nano:shapes><nano:shape id="S">
      <nano:carry ref="Order" />
      <nano:extend name="approved" type="boolean" />
    </nano:shape></nano:shapes>
  </bpmn:extensionElements></bpmn:process>`;
  assert.deepEqual(scanModelMeta(xml), []);
});

test("scanModelMeta ignores a meta with no key; a missing value folds to empty string", () => {
  const xml = `<bpmn:process id="p"><bpmn:extensionElements>
    <nano:meta value="orphan" />
    <nano:meta key="flag" />
  </bpmn:extensionElements></bpmn:process>`;
  assert.deepEqual(scanModelMeta(xml), [{ process: "p", key: "flag", value: "" }]);
});

test("deriveMeta is deterministic and emits nano-generated/meta.ts", () => {
  const models = [{ path: "processes/orders.bpmn", xml: XML }];
  const a1 = deriveMeta(models);
  const a2 = deriveMeta(models);
  assert.deepEqual(a1, a2);
  assert.equal(a1[0].path, "nano-generated/meta.ts");
  assert.equal(a1[0].content, GOLDEN_MULTI);
});

test("deriveMeta folds across models in path order (last write wins)", () => {
  const mk = (id: string, v: string) =>
    `<bpmn:process id="${id}"><bpmn:extensionElements><nano:meta key="env" value="${v}" /></bpmn:extensionElements></bpmn:process>`;
  // Provided out of path order; the deriver sorts by path so `b.bpmn` (prod) wins.
  const models = [
    { path: "processes/b.bpmn", xml: mk("b", "prod") },
    { path: "processes/a.bpmn", xml: mk("a", "staging") },
  ];
  const content = deriveMeta(models)[0].content;
  assert.match(content, /m\["env"\] = "prod";/);
  assert.doesNotMatch(content, /"staging"/);
});
